# Generated by Django 3.0.2 on 2020-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadd',
            name='Academicyear',
            field=models.CharField(max_length=20),
        ),
    ]
