# Generated by Django 3.0.2 on 2020-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200124_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadd',
            name='ParentMbno',
            field=models.CharField(max_length=20),
        ),
    ]
