# Generated by Django 3.0.2 on 2020-01-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200124_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datadds',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Mbno', models.CharField(max_length=20)),
                ('Gmail', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('Alternate_ContactNum', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=40)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
